FROM node:22-alpine

ARG service_name

ENV NODE_ENV=development

WORKDIR /app

# COPY ./services/$service_name /app
# COPY libs /app/libs

COPY ./services/$service_name/package.json /app/package.json

RUN yarn install --frozen-lockfile

EXPOSE 3000

CMD ["yarn", "start:dev"]
